# Site settings
title: Kleyber
description: Sobre Mim
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Kleyber Melo
user_description: Sou Professor de Matemática. Acesse meu currículo aqui http://lattes.cnpq.br/799354200385778
user_title: Professor de Matemática
email: kleyberjr2008@hotmail.com
# twitter_username: lorem_ipsum
# github_username:  lorem_ipsum
# gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
